config/routes.rb
BlogLiquid::Application.routes.draw do
  resources :blogs

  resources :users

  resources :articles    
  
  root :to => 'blogs'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  belongs_to :blog
  validates_presence_of :name, :content
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles, :dependent => :destroy 
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :author_name, :content   
  belongs_to :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery 
  private

   def load_blog
     @current_blog = Blog.find_by_subdomain(current_subdomain)
     if @current_blog.nil?
       flash[:error] = "Blog invalid"
       redirect_to root_url
     else
       self.class.layout(@current_blog.layout_name || 'application')
     end
   end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, :notice => 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :load_blog, :only => :show
  
  def index
    @blogs = Blog.find(:all)
  end
  
  def show
    @blog = @current_blog
  end
  
  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.new(params[:blog])
    if @blog.save
      flash[:notice] = "Successfully created blog."
      redirect_to blogs_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(params[:blog])
      flash[:notice] = "Successfully updated blog."
      redirect_to blogs_url
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    flash[:notice] = "Successfully destroyed blog."
    redirect_to blogs_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :load_blog
  
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end  
  
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= error_messages_for :article %>
<% form_for @article do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/articles/edit.html.erb
<% title "Edit Article" %>

<%= render 'form' %>

<p>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
</p>

app/views/articles/index.html.erb
<% title "Articles" %>

<div id="articles">
<% for article in @articles %>
  <h2>
    <%= link_to h(article.name), article %>
    <span class="users">(<%= pluralize(article.users.size, 'user') %>)</span>
  </h2>
  <div class="author">from <%=h article.author_name %> on <%= article.created_at.strftime('%b %d, %Y') %></div>
  <div class="content"><%= simple_format(article.content) %></div>
<% end %>
</div>

app/views/articles/new.html.erb
<%title "New Article" %>

<%= render 'form' %>

<p><%= link_to 'Back', articles_path %>    </p>

app/views/articles/show.html.erb
<% title @article.name %>

<p class="author"><em>from <%=h @article.author_name %></em></p>

<%=simple_format @article.content %>

<p><%= link_to "Back to Articles", articles_path %></p>

<% unless @article.users.empty? %>
  <h2><%= pluralize(@article.users.size, 'user') %></h2>

  <div id="users">
  <% for user in @article.users %>
    <div class="user">
      <strong><%= link_to_unless user.site_url.blank?, h(user.author_name), h(user.site_url) %></strong>
      <em>on <%= user.created_at.strftime('%b %d, %Y at %H:%M') %></em>
      <%=simple_format user.content %>
    </div>
  <% end %>
  </div>
<% end %>

<h3>Add your user:</h3>
<%= render :partial => 'users/form' %>

app/views/blogs/_form.html.erb
<%= error_messages_for :blog %>
<% form_for @blog do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :subdomain %><br />
    <%= f.text_field :subdomain %>
  </p>
  <p>
    <%= f.label :layout_name %><br />
    <%= f.select :layout_name, [["Standard", 'application'], ["Plain", 'plain'], ["Custom", 'custom']] %>
  </p>
  <p>
    <%= f.label :custom_layout_content %><br />
    <%= f.text_area :custom_layout_content, :rows => 12 %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/blogs/edit.html.erb
<% title "Edit Blog" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @blog %> |
  <%= link_to "View All", blogs_path %>
</p>

app/views/blogs/index.html.erb
<% title "Blogs" %>

<% for blog in @blogs %>
  <div>
    <h2><%= link_to blog.name, blog_root_url(:subdomain => blog.subdomain) %></h2>
    <div class="actions">
      <%= link_to "Edit", edit_blog_path(blog) %> |
      <%= link_to "Destroy", blog, :confirm => 'Are you sure?', :method => :delete %>
    </div>
  </div>
<% end %>

<p><%= link_to "New Blog", new_blog_path %></p>

app/views/blogs/new.html.erb
<% title "New blog" %>

<%= render 'form' %>

<p><%= link_to 'Back', blogs_path %></p>

app/views/blogs/show.html.erb
<% title @blog.name %>

<div id="articles">
<% for article in @blog.articles %>
  <h2>
    <%= link_to h(article.name), article %>
    <span class="comments">(<%= pluralize(article.comments.size, 'comment') %>)</span>
  </h2>
  <div class="author">from <%=h article.author_name %> on <%= article.created_at.strftime('%b %d, %Y') %></div>
  <div class="content"><%= simple_format(article.content) %></div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogLiquid</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/custom.html.erb
<%= Liquid::Template.parse(@current_blog.custom_layout_content).
      render('page_content' => yield, 'page_title' => yield(:title)) %>

app/views/layouts/plain.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      
      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= error_messages_for :comment %>
<% form_for @comment do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, 'Name' %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :site_url, 'Website URL' %><br />
    <%= f.text_field :site_url %>
  </p>
  <p>
    <%= f.label :content, 'Comment' %><br />
    <%= f.text_area :content, :rows => '12', :cols => 35 %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Edit Comment" %>

<%= render :partial => 'form' %>

app/views/users/new.html.erb
<% title "New Comment" %>

<%= render :partial => 'form' %>